version: '3'
services:
  sonarr:
    container_name: sonarr  
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      PUID: 1029
      PGID: 65536
      TZ: Europe/Dublin
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume1/docker/sonarr/downloads:/downloads      
      - /volume1/media/tv:/tv
    ports:
      - 8989:8989
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:8989
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 1m00s

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      PUID: 1027
      PGID: 65536
      TZ: Europe/Dublin
      WEBUI_PORT: 8090
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/data/torrents:/downloads
    ports:
      - 8090:8090
      - 6881:6881
      - 6881:6881/udp
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:8090/api/v2/app/version
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s